#!/usr/bin/env ansible-playbook

- hosts: all
  become: yes
  become_method: sudo
 
  vars:

    swap_file_path: "/swapfile"
    swap_file_size_mb: "512"
  

  tasks:

  - name: Create swap file
    command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_mb }}k
             creates="{{ swap_file_path }}"
    tags:
      - swap.file.create

  - name: Change swap file permissions
    file: path="{{ swap_file_path }}"
          owner=root
          group=root
          mode=0600
    tags:
      - swap.file.permissions

  - name: Check swap file type
    command: file {{ swap_file_path }}
    register: swapfile
    tags:
      - swap.file.mkswap

  - name: Make swap file
    command: "mkswap {{ swap_file_path }}"
    when: swapfile.stdout.find('swap file') == -1
    tags:
      - swap.file.mkswap

  - name: Write swap entry in fstab
    mount: name=none
           src={{ swap_file_path }}
           fstype=swap
           opts=sw
           passno=0
           dump=0
           state=present
    tags:
      - swap.fstab

  - name: Mount swap
    command: "swapon {{ swap_file_path }}"
    when: ansible_swaptotal_mb < 1
    tags:
      - swap.file.swapon

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Install basic list of packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      update_cache: yes

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: ['docker-ce','docker-ce-cli']
      state: present

  - name: Install pip
    apt:
      name: ['python-pip']
      state: present

  - name: Install docker-py package
    pip:
      name: ['docker-py']

  - name: Create docker-nginx Container
    docker_container:
      name: docker-nginx
      image: nginx
      ports:
        - "80:80"
      privileged: true
